name: app_video_player
description: A custom video player package for Coffee Bean project supporting Server MP4/HLS.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.10.1
  chewie: ^1.13.0
  # video_player: ^2.9.1
  # chewie: ^1.10.0 # Good
  # To support YouTube in the future youtube_player_flutter, add:
