name: coffee_bean_db
description: Local database module using Isar for Coffee Bean project.
version: 1.0.0
publish_to: 'none'

environment:
  # xem xet hard fix ^3.11.4
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  isar_community: ^3.3.2
  isar_community_flutter_libs: ^3.3.2

  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  isar_community_generator: ^3.3.2
  build_runner: ^2.15.0

# Su dung isar-community, mot phien ban update cua isar, ho tro fix bugs tot hon
# install link https://isar-community.dev/v3/tutorials/quickstart.html
# dart run build_runner build
