name: coffee_bean_db
description: Local database module using Isar for Coffee Bean project.
version: 1.0.0
publish_to: 'none'

environment:
  # xem xet hard fix ^3.11.4
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

# Su dung
# install link https://isar.dev/tutorials/quickstart.html#_1-add-dependencies
# dart run build_runner build
