import 'course_order_model.dart';

final List<CourseOrderModel> mockCourseOrders = [
  CourseOrderModel(
    id: "1",
    title: "Khóa học Flutter nâng cao 2024",
    description: "Làm chủ kiến trúc RIBs và kiến thức chuyên sâu về Dart. Hướng dẫn xây dựng ứng dụng quy mô lớn.",
    imageUrl: "https://via.placeholder.com/150",
    price: 1100000,
    discountPrice: 688000,
    status: CourseOrderStatus.pending,
    createdAt: DateTime.now().subtract(const Duration(minutes: 15)),
    expiredAt: DateTime.now().add(const Duration(minutes: 15)),
  ),
  CourseOrderModel(
    id: "2",
    title: "Thiết kế UI/UX cho ứng dụng di động",
    description: "Học cách thiết kế giao diện đẹp và trải nghiệm người dùng tối ưu trên Figma.",
    imageUrl: "https://via.placeholder.com/150",
    price: 950000,
    discountPrice: 450000,
    status: CourseOrderStatus.completed,
    createdAt: DateTime.now().subtract(const Duration(days: 1)),
  ),
  CourseOrderModel(
    id: "3",
    title: "Lập trình Backend với Node.js",
    description: "Xây dựng hệ thống API mạnh mẽ, bảo mật và khả năng mở rộng cao.",
    imageUrl: "https://via.placeholder.com/150",
    price: 1200000,
    discountPrice: 890000,
    status: CourseOrderStatus.cancelled,
    createdAt: DateTime.now().subtract(const Duration(days: 2)),
  ),
  CourseOrderModel(
    id: "4",
    title: "Khóa học Dart Core & Functional Programming",
    description: "Nắm vững nền tảng Dart để tối ưu hóa hiệu năng ứng dụng Flutter.",
    imageUrl: "https://via.placeholder.com/150",
    price: 800000,
    discountPrice: 550000,
    status: CourseOrderStatus.completed,
    createdAt: DateTime.now().subtract(const Duration(days: 3)),
  ),
  CourseOrderModel(
    id: "5",
    title: "Lập trình Web với React & Next.js",
    description: "Xây dựng ứng dụng web hiện đại, tối ưu SEO và trải nghiệm người dùng.",
    imageUrl: "https://via.placeholder.com/150",
    price: 1500000,
    discountPrice: 1100000,
    status: CourseOrderStatus.pending,
    createdAt: DateTime.now().subtract(const Duration(days: 4)),
    expiredAt: DateTime.now().add(const Duration(minutes: 5)),
  ),
  CourseOrderModel(
    id: "6",
    title: "Python cho Khoa học dữ liệu",
    description: "Phân tích dữ liệu, trực quan hóa và làm quen với thư viện Pandas, NumPy.",
    imageUrl: "https://via.placeholder.com/150",
    price: 1350000,
    discountPrice: 990000,
    status: CourseOrderStatus.completed,
    createdAt: DateTime.now().subtract(const Duration(days: 5)),
  ),
  CourseOrderModel(
    id: "7",
    title: "Nhập môn Trí tuệ nhân tạo (AI)",
    description: "Hiểu về Machine Learning, Deep Learning và các ứng dụng thực tế của AI.",
    imageUrl: "https://via.placeholder.com/150",
    price: 2000000,
    discountPrice: 1500000,
    status: CourseOrderStatus.cancelled,
    createdAt: DateTime.now().subtract(const Duration(days: 6)),
  ),
  CourseOrderModel(
    id: "8",
    title: "Android Jetpack Compose Toàn tập",
    description: "Học cách xây dựng UI Android hiện đại bằng Declarative framework.",
    imageUrl: "https://via.placeholder.com/150",
    price: 900000,
    discountPrice: 650000,
    status: CourseOrderStatus.completed,
    createdAt: DateTime.now().subtract(const Duration(days: 7)),
  ),
  CourseOrderModel(
    id: "9",
    title: "Digital Marketing cho Người mới bắt đầu",
    description: "Nắm vững các kênh Facebook Ads, Google Ads và chiến lược Content.",
    imageUrl: "https://via.placeholder.com/150",
    price: 750000,
    discountPrice: 390000,
    status: CourseOrderStatus.pending,
    createdAt: DateTime.now().subtract(const Duration(days: 8)),
    expiredAt: DateTime.now().add(const Duration(minutes: 45)),
  ),
  CourseOrderModel(
    id: "10",
    title: "An toàn thông tin & Bảo mật mạng",
    description: "Các kiến thức cơ bản về phòng chống tấn công mạng và bảo vệ dữ liệu.",
    imageUrl: "https://via.placeholder.com/150",
    price: 1800000,
    discountPrice: 1250000,
    status: CourseOrderStatus.completed,
    createdAt: DateTime.now().subtract(const Duration(days: 9)),
  ),
  CourseOrderModel(
    id: "11",
    title: "SQL & Thiết kế Cơ sở dữ liệu",
    description: "Tối ưu truy vấn SQL và thiết kế cấu trúc DB cho ứng dụng phức tạp.",
    imageUrl: "https://via.placeholder.com/150",
    price: 850000,
    discountPrice: 480000,
    status: CourseOrderStatus.cancelled,
    createdAt: DateTime.now().subtract(const Duration(days: 10)),
  ),
  CourseOrderModel(
    id: "12",
    title: "Kiến trúc Microservices với Docker & K8s",
    description: "Triển khai hệ thống phân tán mạnh mẽ và khả năng mở rộng không giới hạn.",
    imageUrl: "https://via.placeholder.com/150",
    price: 2500000,
    discountPrice: 1950000,
    status: CourseOrderStatus.pending,
    createdAt: DateTime.now().subtract(const Duration(days: 11)),
    expiredAt: DateTime.now().subtract(const Duration(minutes: 10)), // Already expired
  ),
  CourseOrderModel(
    id: "13",
    title: "Quản trị dự án Agile/Scrum",
    description: "Cách vận hành quy trình phát triển phần mềm hiệu quả theo mô hình Agile.",
    imageUrl: "https://via.placeholder.com/150",
    price: 1100000,
    discountPrice: 720000,
    status: CourseOrderStatus.completed,
    createdAt: DateTime.now().subtract(const Duration(days: 12)),
  ),
  CourseOrderModel(
    id: "14",
    title: "Lập trình iOS với Swift & SwiftUI",
    description: "Xây dựng ứng dụng iPhone/iPad chuyên nghiệp với ngôn ngữ Swift mới nhất.",
    imageUrl: "https://via.placeholder.com/150",
    price: 1600000,
    discountPrice: 1150000,
    status: CourseOrderStatus.completed,
    createdAt: DateTime.now().subtract(const Duration(days: 13)),
  ),
];
