name: coffee_bean_core
description: Core module for Coffee Bean project containing shared utilities and architecture.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5

  isar: 4.0.0
  isar_flutter_libs: 4.0.0 # contains Isar Core

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.15.0
