import 'package:coffee_bean/data/model/response/system/notify_message.dart';

final mockNotifyMessages = [
  NotifyMessage(
    id: 1,
    userId: 1024,
    userType: "1",
    templateId: 101,
    templateCode: "COMMENT_NOTIFY",
    templateNickname: "Hệ thống",
    templateContent: 'Có **GiGi** đã bình luận về bài viết của bạn "Wow ôi thật hay n..."',
    templateType: 2,
    templateParams: {},
    readStatus: false,
    createTime: DateTime.now().millisecondsSinceEpoch,
  ),
  NotifyMessage(
    id: 2,
    userId: 1024,
    userType: "1",
    templateId: 101,
    templateCode: "COMMENT_NOTIFY",
    templateNickname: "Hệ thống",
    templateContent: 'Có **Hungcute** đã bình luận về bài viết của bạn "Wow ôi thật hay n..."',
    templateType: 2,
    templateParams: {},
    readStatus: true,
    createTime: DateTime.now().subtract(const Duration(days: 1)).millisecondsSinceEpoch,
  ),
  NotifyMessage(
    id: 3,
    userId: 1024,
    userType: "1",
    templateId: 102,
    templateCode: "SYSTEM_NOTIFY",
    templateNickname: "Admin",
    templateContent: 'Chào mừng bạn đến với Coffee Bean. Hãy bắt đầu trải nghiệm ngay hôm nay!',
    templateType: 1,
    templateParams: {},
    readStatus: false,
    createTime: DateTime.now().subtract(const Duration(days: 3)).millisecondsSinceEpoch,
  ),
  NotifyMessage(
    id: 4,
    userId: 1024,
    userType: "1",
    templateId: 101,
    templateCode: "COMMENT_NOTIFY",
    templateNickname: "Hệ thống",
    templateContent: 'Có **User123** đã thích bài viết của bạn.',
    templateType: 2,
    templateParams: {},
    readStatus: true,
    createTime: DateTime.now().subtract(const Duration(days: 8)).millisecondsSinceEpoch,
  ),
];
