# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# Tối ưu cho hiển thị log
$stdout.sync = true

default_platform(:ios)

platform :ios do
  # Khai báo tester đồng bộ với Android
  DEV_TESTERS = "buivantienduc@gmail.com"
  DEV_GROUPS = "dev-tmlabs"

  lane :deploy do |options|
      env = options[:env] || "dev"
      target = get_target_path(env)

      UI.header "🚀 Quy trình Deploy iOS [#{env.upcase}]"

      # 1. Định nghĩa export_method dựa trên môi trường
      # TestFlight BẮT BUỘC dùng 'app-store'
      export_method = (env == "production") ? "app-store" : "ad-hoc"

      # 2. Build IPA
      UI.message("🛠  Building IPA for flavor: #{env} with export-method: #{export_method}...")
      Dir.chdir "../.." do
        sh("flutter", "build", "ipa", "--flavor", env, "-t", target, "--export-method", export_method)
      end

      # 3. Phân phối
      if env == "production"
        # --- ĐƯA LÊN TESTFLIGHT ---
        upload_to_testflight(
          # skip_waiting_for_build_processing: true, # Tiết kiệm thời gian trên CI
          # apple_id: "ID_CỦA_APP_TRÊN_APP_STORE_CONNECT",
          ipa: "../build/ios/ipa/*.ipa"
        )
        UI.success "✅ Đã tải bản build lên TestFlight thành công!"
      else
        # --- ĐƯA LÊN FIREBASE ---
        app_id = get_firebase_app_id(env)
        firebase_app_distribution(
          app: app_id,
          testers: DEV_TESTERS,
          #groups: DEV_GROUPS,
          release_notes_file: '../release-notes.txt',
          ipa_path: "../build/ios/ipa/*.ipa"
        )
        UI.success "✅ Đã tải bản build [#{env}] lên Firebase!"
      end
    end

  end

  # ==============================================================
  # HELPER METHODS
  # ==============================================================

  # Hàm xác định file main (Giống hệt Android)
  def get_target_path(env)
    target_map = {
      "dev"        => "lib/main_dev.dart",
      "uat"        => "lib/main_uat.dart",
      "production" => "lib/main_release.dart"
    }
    target = target_map[env] || "lib/main.dart"
    UI.important "📍 Target Path: #{target}"
    target
  end

  # Hàm xác định App ID iOS (Bạn cần thay ID iOS từ Firebase Console)
  def get_firebase_app_id(env)
    app_id_map = {
      "dev"        => "1:583923309178:ios:xxxxxx_DỔI_ID_TẠI_ĐÂY_xxxxxx",
      "uat"        => "1:583923309178:ios:yyyyyy_DỔI_ID_TẠI_ĐÂY_yyyyyy",
      "production" => "1:583923309178:ios:zzzzzz_DỔI_ID_TẠI_ĐÂY_zzzzzz"
    }
    id = app_id_map[env]
    UI.important "📱 Firebase iOS App ID: #{id}"
    id
  end


end