# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# Tối ưu cho hiển thị log
$stdout.sync = true

default_platform(:android)

platform :android do

  # Khai báo danh sách tester trực tiếp tại đây
  DEV_TESTERS = "buivantienduc@gmail.com"
  DEV_GROUPS = "tm-labs-qa"

  lane :deploy do |options|

        # Đọc version từ pubspec.yaml
        # pubspec = YAML.load_file("../../pubspec.yaml")
        # version_name = pubspec['version'].split('+')[0]
        # build_number = pubspec['version'].split('+')[1]

        env = options[:env] || "dev"
        # Xác định file main dựa trên môi trường
        target = get_target_path(env)
        # Get App ID - Distribution
        app_id = get_firebase_app_id(env)

        # Build APK với flavor tương ứng
        UI.message("🛠  Building APK for flavor: #{env} with target: #{target}...")
        Dir.chdir "../.." do
          sh("flutter", "build", "apk", "--flavor", env, "-t", target)
        end

        # testers: (env == "production") ? PROD_TESTERS : DEV_TESTERS,
        # groups: (env == "production") ? PROD_GROUPS : DEV_GROUPS,

        # 2. Phân phối qua Firebase App Distribution [cite: 2, 5, 10]
        firebase_app_distribution(
          app: app_id,
          testers: DEV_TESTERS,
          #groups: DEV_GROUPS,
          # service_credentials_file: ENV["GOOGLE_APPLICATION_CREDENTIALS"],
          release_notes_file: '../release-notes.txt',
          # release_notes: "Bản build: #{version_name} (Build: #{build_number}) cho #{env.upcase}",

          android_artifact_type: "APK",
          android_artifact_path: "../build/app/outputs/flutter-apk/app-#{env}-release.apk"

          # Build AAB file replace for APK
          # android_artifact_type: "AAB",
          # android_artifact_path: "../build/app/outputs/bundle/#{env}Release/app-#{env}-release.aab"
          # debug: true # Print debug log to terminal
        )

  end

  # ==============================================================
  # HELPER METHODS
  # ==============================================================

  # Hàm xác định file main dựa trên môi trường
  def get_target_path(env)
    target_map = {
      "dev"        => "lib/main_dev.dart",
      "uat"        => "lib/main_uat.dart",
      "production" => "lib/main_release.dart"
    }
    target = target_map[env] || "lib/main.dart"
    UI.message("🚀 Target Path: #{target}")
    target
  end

  # Hàm xác định App ID dựa trên môi trường
  def get_firebase_app_id(env)
    app_id_map = {
      "dev"        => "1:583923309178:android:08a48518329ab1935f39c3",
      "uat"        => "1:583923309178:android:f0aa44b8fe04aa2f5f39c3",
      "production" => "1:583923309178:android:b2e7424894b6ea015f39c3"
    }
    app_id_map[env]
  end



end